#!/bin/bash
person1=$1
person2=$2

echo "$person1:hello, how are you"
echo "$person2:Am fine how are you"
echo "$person1: fine too, what is your career plan"
echo "$person2: Am planning to learn devops"
echo "$person1: Good practice well and get good job"